name: Release New Version

on:
  push:
    tags: ['v*']

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/solid-tiptap

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build package
        run: pnpm run build

      - name: Pack tarball
        run: |
          mkdir -p ../../artifacts
          pnpm pack --pack-destination ../../artifacts
          mv ../../artifacts/solid-tiptap-*.tgz ../../artifacts/solid-tiptap.tgz

      - uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*.tgz